### ISSUE TITLE
QTPY S2 - Analog 0 is at 3.3v when set as potentiometer input

### ISSUE THREAD

**Issue by tyeth** [adafruit/Wippersnapper_Boards#101]
-EDIT- _&lt;TLDR&gt;_ **It's part of the specification, the first analog input (A0) has (and requires in the datasheet) a 10k pullup resistor, which will affect things if unaware.** [see comment](https://github.com/adafruit/Wippersnapper_Boards/issues/101#issuecomment-1549809697)

Heya, was using potentiometer to represent a soil sensor. and the input was always maxed except when I hardwired it to ground.
turns out that A0 is always 3.3v, but choosing A1-3 works as expected

Device ID if useful
https://io.adafruit.com/tyeth/devices/qtpy-esp32s214035171

**Comment by tyeth** [comment]
could well be my fault, but I haven't tested another similar device yet, be a slow progress one sorry

**Comment by brentru** [comment]
Hrm, A0 is mapped to D18 both [in the arduino-esp32 variant](https://github.com/espressif/arduino-esp32/blob/master/variants/adafruit_qtpy_esp32s2/pins_arduino.h#L41) and the [WipperSnapper definition](https://github.com/adafruit/Wippersnapper_Boards/blob/main/boards/qtpy-esp32s2/definition.json#L13).


Could you test this via an Arduino Sketch, or CircuitPython Sketch, to rule out WipperSnapper being the culprit. Something like:

```
int analogPin = D18; // potentiometer wiper (middle terminal) connected to analog pin A0
                    // outside leads to ground and +5V
int val = 0;  // variable to store the value read

void setup() {
  Serial.begin(9600);           //  setup serial
}

void loop() {
  val = analogRead(analogPin);  // read the input pin
  Serial.println(val);          // debug value
}
```

**Comment by tyeth** [comment]
I've now managed to return to the device and find it missing the boot button. Like I live alone and it hasn't been abused in theory (reattached peripheral once and it's dangling freely so potenially my bad) but pretty surprised by this. I think I'll have to find a second device to test.
![20230501_152810](https://user-images.githubusercontent.com/6692083/235534626-7b253145-2fbb-4b05-b1b7-cbee9b44864a.jpg)

**Comment by tyeth** [comment]
Just to note, it may have been an artifact of arduino-esp32 v2.0.8, in v2.0.9 (latest) this fixed an issue with second use of analogWrite being ignored:
https://github.com/espressif/arduino-esp32/pull/8137

**Comment by brentru** [comment]
@tyeth The latest build of Wippersnapper is on v2.0.9.

**Comment by tyeth** [comment]
@brentru You'll be somewhat relieved to hear the behaviour is the same with latest wippersnapper on a new-ish qtpy. A0 (listed as A18 in serial) always registers 65k when set as potentiometer. Using A1 (listed as A17 in serial) is fine. It's a capacitive soil sensor remember.

In arduino land, with the code you wrote (i had to change D18 to A0 and A1) then A0 gave 8192 with nothing connected (floating) and same with my soil sensor connected (no matter with or without wet soil or held in fingers).
The A1 input gives between 4 and 5 hundred floating, and 7600 with no soil (unheld) and 3100 when held.

What do you get with a qtpy s2(or s3 probably) and A0 or A1 floating and then with something to read?

**Comment by brentru** [comment]
> In arduino land, with the code you wrote (i had to change D18 to A0 and A1) then A0 gave 8192 with nothing connected (floating) and same with my soil sensor connected (no matter with or without wet soil or held in fingers).

From the Learn Guide...
"Note that A0 has a 10K pullup to 3.3V - we're not sure why but this is [required by the hardware design notes for the ESP32-S2 (see Fig 1).](https://www.espressif.com/sites/default/files/documentation/esp32-s2_hardware_design_guidelines_en.pdf)"

**Comment by tyeth** [comment]
Well that explains it. Yeah I wonder if a note could be added for individual pins, so for any non pull-up or adc differential pairs, or unexpected things like this, rather than hiding functionality. Maybe when you select a pin the name has an asterisk and once selected the UI could show a label or link to notes (or rely on product link)

**Comment by brentru** [comment]
@lorennorman  See above, maybe something to implement.

@tyeth  For now, we can either hide the A0 pin or keep this issue open for others. Either works!

**Comment by tyeth** [comment]
Happy either way!
