### ISSUE TITLE
Magic Config files for all boards

### ISSUE THREAD

**Issue by lorennorman** [adafruit/Wippersnapper_Boards#129]
Every board at least has a built-in LED and/or button, so every board will benefit from a magic config file. Let's create them all!

Step-by-step process for creation a Magic Config file:
- until #127 is merged:
  - branch from #127
  - use the app in staging
- pick a board to do
- create/connect the board
- add every built-in component possible, ensure they're working as expected
  - open new issues if you find busted things in the regular board json
- export a config file and open it for editing
- ensure `exportVersion` is `1.0.0`
- set `exportedBy` to `Adafruit` (repo validates this for now)
- add `"selected": false` to components that should appear, but should not be checked for import by default
  - C & F temperature types
  - duplicated functionality
- rename to `magic.json` and add to the board's directory next to `definition.json`

Ping me if you need a re-import of this branch to test your work.

**Comment by tyeth** [comment]
@lorennorman branched on https://github.com/adafruit/Wippersnapper_Boards/tree/all-magic-configs
If you wouldn't mind updating staging with that branch, so that I can use the newly added boot0 buttons as part of the magic configs, it would be much appreciated.

**Comment by tyeth** [comment]
Closing this as complete, Magic Configs were made live at the end of last year!
