### ISSUE TITLE
[REQUEST] Adafruit Metro ESP32-S3

### ISSUE THREAD

**Issue by brentru** [adafruit/Wippersnapper_Boards#154]
**Name of Board**
Adafruit Metro ESP32-S3

**Board Architecture (i.e: SAMD51, ESP32-S2, ESP32, ...)**
ESP32-S3

**Hardware URL**
https://www.adafruit.com/product/5500

https://learn.adafruit.com/adafruit-metro-esp32-s3

**Comment by tyeth** [comment]
Closed by #169
