### ISSUE TITLE
[REQUEST] PyPortal Titano

### ISSUE THREAD

**Issue by brentru** [adafruit/Wippersnapper_Boards#25]
**Name of Board**
PyPortal Titano

**Board Architecture (i.e: SAMD51, ESP32-S2, ESP32, ...)**
SAMD51 + ESP32 AirLift

**Hardware URL**
https://www.adafruit.com/product/4444

**Pinout URL**
https://github.com/adafruit/ArduinoCore-samd/tree/master/variants/pyportal_m4_titano

**Additional context**
Add any other context about the board request here.

**Comment by Hexen-Wulf** [comment]
Thank you for adding this. I've been wondering why the Titano wasn't supported on Wippersnapper, and this will put my mind at ease.

**Comment by AGnepp** [comment]
I just got my PyPortal Titano and would love full hardware support for it via Adafruit IO.

**Comment by brentru** [comment]
@tyeth  Want to take this on?

**Comment by tyeth** [comment]
Yep, now on my list to look at this week

**Comment by brentru** [comment]
This board is supported by Adafruit.io WipperSnapper
